language: generic
sudo: required
dist: trusty
compiler:
  - gcc
env:
  global:
    - PATCHSET_NDNCXX=master
    - PATCHSET_NDNTOOLS=3556,6
  matrix:
    - PROJECT=NFD-benchmark
    - PROJECT=ndn-cxx-integ
    - PROJECT=ndn-tools
install:
  - ./deps_ndn-cxx.sh
  - 'if [[ -f ./deps_${PROJECT}.sh ]]; then ./deps_${PROJECT}.sh; fi'
before_script:
  - ./build_ndn-cxx.sh
script:
  - './build_${PROJECT}.sh'
notifications:
  email:
    recipients:
      - sunnylandh@gmail.com
    on_success: always
    on_failure: always
