language: generic
sudo: required
dist: trusty
compiler:
  - gcc
env:
  global:
    - PATCHSET_NDNCXX=3546,13
    - PATCHSET_NFD=master
    - PATCHSET_NLSR=master
    - PATCHSET_NDNTOOLS=master
    - PATCHSET_NDNS=master
    - PATCHSET_REPONG=master
    - PATCHSET_CHRONOSYNC=master
    - PATCHSET_TRAFFICGEN=master
    - PATCHSET_INTEG=master
  matrix:
    - PROJECT=NFD
    - PROJECT=NFD-benchmark
    - PROJECT=ndn-cxx-integ
    - PROJECT=NLSR
    - PROJECT=ChronoChat
    - PROJECT=ChronoSync
    - PROJECT=ndns
    - PROJECT=repo-ng
    - PROJECT=ndn-tools
    - PROJECT=ndn-traffic-generator
install:
  - ./deps_ndn-cxx.sh
  - 'if [[ -f ./deps_${PROJECT}.sh ]]; then ./deps_${PROJECT}.sh; fi'
before_script:
  - ./build_ndn-cxx.sh
script:
  - './build_${PROJECT}.sh'
notifications:
  email:
    recipients:
      - sunnylandh@gmail.com
    on_success: always
    on_failure: always
